services:
services:
  - type: web
    name: task-queue-api
    runtime: python
    rootDir: backend
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: falseEST_TOKEN
        sync: false

  - type: worker
    name: task-queue-worker
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m worker.worker
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false